#!/bin/env bash
function fail {
	printf '%s\n' "$1" >&2 # message to stderr
	exit "${2-1}"          # return code specified by $2, or 1 by default
}

# top-level file (remember to change these variables accordingly)
PROJ_DIR="."
PROJ_NAME=$(basename $(ls ${PROJ_DIR}/src/*.cpp| head -1) | sed 's/.cpp//g')
TOP_FILE="${PROJ_NAME}.cpp"

#============================================================================================================#

# clock period
for i in "$@"; do
	case $i in
	-c=*|--clock_period=*|-period=*)
	CLOCK_PERIOD="${i#*=}"
	shift ;;
	*) ;;
	esac
done

[ -z $PROJ_NAME ] && fail "no top file can be found"

[ -z "$CLOCK_PERIOD" ] && echo "info - clock period is not set: using default cp=4" && CLOCK_PERIOD=4

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

bash ${SCRIPT_DIR}/write_tcl.sh --top=${PROJ_NAME} --clock=${CLOCK_PERIOD}

vivado-2019.1.1-bt vivado -mode tcl -source ./synthesis.tcl
